# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  buildNdeploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - run: |
          {
            echo 'db.default.url = jdbc:postgresql://10.0.0.251:5432/ks-v7';
            echo 'db.default.user = postgres';
            echo 'db.default.password = postgres';
          } >> src/main/resources/axelor-config.properties


      - run: ./gradlew -x test build

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "build/libs/axelor-erp-7.0.0.war"
          target: "~/"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/tomcat
            docker compose down
            cd ~/tomcat/ks-erp
            git pull
            sed -i "/random/c\select ${RANDOM} as random;" src/main/resources/db/migration/R__reset-modules.sql
            {
                echo 'db.default.url = jdbc:postgresql://10.0.0.251:5432/ks-v7';
                echo 'db.default.user = postgres';
                echo 'db.default.password = postgres';
            } >> src/main/resources/axelor-config.properties
            ./gradlew database --migrate
            git checkout .  
            cd ~/tomcat
            sudo rm -rf webapps/{ROOT, ROOT.war}
            sudo mv ~/build/libs/axelor-erp-7.0.0.war webapps/ROOT.war
            docker compose up -d
